# Create env:
# $ conda env create --force

name: timeseries
dependencies:
  - python = 2.7
  - ipython > 5
  - jupyter >= 1.0
  - numpy >= 1.11
  - pandas >= 0.18
  - matplotlib >= 1.5
  - scikit-learn >= 0.17
  - setuptools
  - psutil
     
# Start env:
# $ source activate timeseries